### ISSUE TITLE
是否支持redis sentinal

### ISSUE THREAD

**Issue by chopper-poet** [meitu/lmstfy#13]
是否支持redis sentinal

**Comment by git-hulk** [comment]
目前我们主要是通过 sentinel 的 notify script 修改 DNS 方式来切主从，没有在 client 直接兼容 sentinel

**Comment by git-hulk** [comment]
@chopper-poet 目前已经支持 Sentinel

**Comment by chopper-poet** [comment]
> @chopper-poet 已经支持 Sentinel

哈哈，真好，上次我们新项目想用，就是因为对sentinel的支持不好被否了，现在可以搞起了，顺便问一下配置文档在什么地方。

**Comment by git-hulk** [comment]
可以参考 https://github.com/meitu/lmstfy/blob/master/config/demo-conf.toml 的 demo 配置，挺简单，对于 sentinel 只要配置地址和 MasterName

**Comment by chopper-poet** [comment]
关于消费成功完成以后的ack我有点建议，忘采纳：
按照我的理解，当业务处理失败以后不需要ack，等到过了ttr以后又可以consum到，是否可以在失败以后也支持ack，只是这种ack会携带**失败状态**和**下次消费时间**，以此来实现阶梯式重试机制。

**Comment by git-hulk** [comment]
@chopper-poet 这个目前可以通过 ack + publish 新任务来实现就可以

**Comment by chopper-poet** [comment]
> @chopper-poet 这个目前可以通过 ack +publish 新任务来实现。不过不是原子的，你说的这个特性可以最近支持一下。

请问这个特性后来支持了吗

**Comment by git-hulk** [comment]
这个特性在内部讨论过一次，暂时只能实现原子的 ACK + Publish 功能，这个计划在 4 月第一周开发和发布。
