### ISSUE TITLE
为什么不支持批量任务拉取及生成呢？

### ISSUE THREAD

**Issue by shiqwang** [meitu/lmstfy#16]
为什么不支持批量任务拉取及生成呢？
我现在每天爬虫的任务大概有3亿个，一个一个拉取有点太麻烦了

**Comment by git-hulk** [comment]
这个需求挺好的，可以支持。最近打算支持不需要 ack 的拉取场景。

Michael <notifications@github.com> 于2020年1月8日周三 下午1:51写道：

**Comment by git-hulk** [comment]
Resolved #17
