### ISSUE TITLE
死信队列中的消息不会定期清除吗？

### ISSUE THREAD

**Issue by brzyangg** [meitu/lmstfy#18]
请问一下，成功消费的任务也会加入死信队列。这样死信队列中的任务会越来越多。这样不会对性能，内存造成比较大的影响吗？

**Comment by git-hulk** [comment]
这块对于性能不会有影响，影响是内存会有些堆积。然后这块从任务队列本身不应该去主动删除而是应该业务主动来删除或者定时去 purge 整个 dead letter 队列。
