### ISSUE TITLE
现在所有的任务好像都是放在一个zset中

### ISSUE THREAD

**Issue by brzyangg** [meitu/lmstfy#22]
现在所有task好像都默认放在了key = timer_set的zset中，这样还未到期任务太多，这个zset就会很大吧，遍历排序延时增高。这样不会有什么问题吗？
请问这一块是本身就是这样设计的吗？

**Comment by git-hulk** [comment]
@brzyangg 所有的 key 是会在 timer set 里面，zset 的查找时间复杂度是 O(N * log(N))，这块在全内存的查找方面性能方面不会是特大的问题，另外一块就是因为从 zset 迁移到 ready queue 都会比较及时不会导致大规模未过期 key 堆积

**Comment by brzyangg** [comment]
@git-hulk 考虑到如果延迟时间较长的任务比较多。这种情况就会导致大规模未过期的key了。想请问咱们现在实际使用的过程中，没有出现因为zset过大从而导致的问题吗？或者说之后有考虑分多个zset这种的实现吗？

**Comment by git-hulk** [comment]
@brzyangg 目前还没有遇到类似问题，对于多 zset 方案目前没有考虑，因为如果不拆分为每个 queue 独立的 zset 的话帮助不大。现在支持多个 Redis Pool 的方式来拆分数据存储，也可以将一些过期比较长的数据独立存储，一定程度上也可以缓解问题。

我们目前主要重点开发计划是在支持磁盘类型存储方面

**Comment by brzyangg** [comment]
好的，多谢解答。

**Comment by git-hulk** [comment]
客气，我关闭这个 Issue, 如有其它问题再重新打开
