### ISSUE TITLE
过期job如何主动清理

### ISSUE THREAD

**Issue by chopper-poet** [meitu/lmstfy#26]
请问过期的job要如何手动清理呢，我使用delete 删除但是redis中依然存在。下面截图为lmstfy-server打出来的日志。
![image](https://user-images.githubusercontent.com/16041012/73717887-fa93bd80-4755-11ea-966d-0088bbf983ec.png)

**Comment by chopper-poet** [comment]
删除以后依然存在于q/:namespace/:queuename中

**Comment by git-hulk** [comment]
@chopper-poet DELETE 之后会回收，你这边在 Consume 的时候 TTR 设置多大

**Comment by git-hulk** [comment]
@chopper-poet 过期的 Job 虽然在 ready queue 里面，但后面在消费的时候会自动删除掉，不需要手动去删除。

**Comment by chopper-poet** [comment]
> @chopper-poet 过期的 �Job 虽然在 ready queue 里面，但后面在消费的时候会自动删除掉，不需要手动去删除。

测试了一下，确实如此。顺便追问一个问题，我publish一个job，然后使用publish时生成的job对象执行业务逻辑，执行完成以后直接ack，这中间少了一步consume，我测试没有报错，不知道是否违背了当初的设计。

**Comment by git-hulk** [comment]
@chopper-poet  这个发现很赞，是不太对，我们修复一下。

**Comment by git-hulk** [comment]
add issue #27
